### ISSUE TITLE
Parameter data1 (=182) must be in the range 0 to 127

### ISSUE THREAD

**Issue by blablack** [blablack/aurelien_bitwig_extensions#2]
At random using the Launchpad S:
Parameter data1 (=182) must be in the range 0 to 127
zVB: Parameter data1 (=182) must be in the range 0 to 127
    at LWY.inRange(SourceFile:185)
    at com.bitwig.flt.control_surface.proxy.ControlSurfaceObject.inRange(SourceFile:344)
    at com.bitwig.flt.control_surface.proxy.MidiOutPort.sendMidi(SourceFile:21)
    at com.aurelien.NoteMap.setCellLED(NoteMap.java:52)
    at com.aurelien.NoteMapDrums.TurnOnNote(NoteMapDrums.java:45)
    at com.aurelien.LaunchpadExtension.PlayingNotes(LaunchpadExtension.java:187)
    at com.bitwig.flt.control_surface.values.ComputedPlayingNoteArrayValue.notifyObservers(SourceFile:80)
    at com.bitwig.flt.control_surface.values.ComputedPlayingNoteArrayValue.lambda$queueNotifyObservers$0(SourceFile:64)
    at fyC.zuE(SourceFile:94)
    at fyC.Agf(SourceFile:90)
    at u3g.mn(SourceFile:128)
    at xNa.xdW(SourceFile:76)
    at gVa.THb(SourceFile:248)
    at gKZ.zuE(SourceFile:335)
    at cVf.zuE(SourceFile:205)
    at olG.run(SourceFile:91)
    at cVf.run(SourceFile:106)

**Comment by blablack** [comment]
Could reproduce it messing with the drum mode and changing octaves:

Parameter data1 (=182) must be in the range 0 to 127
zVB: Parameter data1 (=182) must be in the range 0 to 127
    at LWY.inRange(SourceFile:185)
    at com.bitwig.flt.control_surface.proxy.ControlSurfaceObject.inRange(SourceFile:344)
    at com.bitwig.flt.control_surface.proxy.MidiOutPort.sendMidi(SourceFile:21)
    at com.aurelien.NoteMap.setCellLED(NoteMap.java:52)
    at com.aurelien.NoteMapDrums.TurnOnNote(NoteMapDrums.java:45)
    at com.aurelien.LaunchpadExtension.PlayingNotes(LaunchpadExtension.java:187)
    at com.bitwig.flt.control_surface.values.ComputedPlayingNoteArrayValue.notifyObservers(SourceFile:80)
    at com.bitwig.flt.control_surface.values.ComputedPlayingNoteArrayValue.lambda$queueNotifyObservers$0(SourceFile:64)
    at fyC.zuE(SourceFile:94)
    at fyC.Agf(SourceFile:90)
    at u3g.mn(SourceFile:128)
    at xNa.xdW(SourceFile:76)
    at gVa.THb(SourceFile:248)
    at gKZ.zuE(SourceFile:335)
    at cVf.zuE(SourceFile:205)
    at olG.run(SourceFile:91)
    at cVf.run(SourceFile:106)
